---
# Example Job for testing PVC backup
apiVersion: batch/v1
kind: Job
metadata:
  name: pvc-backup-test
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: pbs-backup
          # Use GitHub Container Registry image
          image: ghcr.io/fgeck/pbs-k8s-backup:latest
          command: ["/entrypoint.sh", "pvcs"]
          env:
            - name: PVC_HOST_PATH
              value: "/pvcs"
            - name: PROXMOX_BACKUP_SERVER_NAMESPACE
              value: "k3s/pvcs"
          envFrom:
            - secretRef:
                name: pvc-backup-secret
          volumeMounts:
            - name: pvc-path
              mountPath: /pvcs
      restartPolicy: Never
      volumes:
        - name: pvc-path
          hostPath:
            path: /opt/k3s/data
            type: Directory
---
# Example Job for testing PostgreSQL backup
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup-test
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: pbs-backup
          image: ghcr.io/fgeck/pbs-k8s-backup:latest
          command: ["/entrypoint.sh", "postgres"]
          env:
            - name: PROXMOX_BACKUP_SERVER_NAMESPACE
              value: k3s/databases
            - name: BACKUP_NAME
              value: "test-postgres"
          envFrom:
            - secretRef:
                name: default-postgres-backup-secret
            - secretRef:
                name: pvc-backup-secret # For PBS credentials
          volumeMounts:
            - name: temp-backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: temp-backup
          emptyDir:
            sizeLimit: 6Gi
